/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#131317',
        surface: '#131317',
        'surface-dim': '#131317',
        'surface-bright': '#39393d',
        'surface-container-lowest': '#0e0e12',
        'surface-container-low': '#1b1b1f',
        'surface-container': '#1f1f23',
        'surface-container-high': '#2a292e',
        'surface-container-highest': '#353439',
        'surface-variant': '#353439',
        'surface-tint': '#ffb3af',
        'on-surface': '#e4e1e7',
        'on-surface-variant': '#dfbfbd',
        'on-background': '#e4e1e7',
        primary: '#ffb3af',
        'on-primary': '#68000d',
        'primary-container': '#b33a3a',
        'on-primary-container': '#ffdad7',
        'inverse-primary': '#aa3434',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3af',
        'on-primary-fixed': '#410005',
        'on-primary-fixed-variant': '#891b20',
        secondary: '#f5be44',
        'on-secondary': '#402d00',
        'secondary-container': '#b98904',
        'on-secondary-container': '#382700',
        'secondary-fixed': '#ffdea1',
        'secondary-fixed-dim': '#f5be44',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5c4300',
        tertiary: '#c7c5d3',
        'on-tertiary': '#2f2f3b',
        'tertiary-container': '#646370',
        'on-tertiary-container': '#e3e0ef',
        'tertiary-fixed': '#e3e1f0',
        'tertiary-fixed-dim': '#c7c5d3',
        'on-tertiary-fixed': '#1a1b25',
        'on-tertiary-fixed-variant': '#464651',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#a68a88',
        'outline-variant': '#584140',
        'inverse-surface': '#e4e1e7',
        'inverse-on-surface': '#303034',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        unit: '4px',
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['Montserrat'],
        'display-md': ['Montserrat'],
        'headline-lg': ['Montserrat'],
        'headline-lg-mobile': ['Montserrat'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-bold': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '800' }],
        'display-md': ['32px', { lineHeight: '1.2', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['20px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['12px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
